name: tariftest_1
description: Eine Flutter-Anwendung für Tariftest-Eingaben.

# Die folgende Zeile verhindert, dass Ihr Paket veröffentlicht wird.
# Dies ist besonders wichtig, wenn das Paket Betriebsgeheimnisse enthält.
publish_to: 'none' 

# Versionsnummer für Ihre Anwendung
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # mySQL Datenbank
  mysql1: ^0.20.0
  
  # UI und Widgets
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.19.0  # Aktualisiert von ^0.18.0 auf ^0.19.0
  file_picker: ^5.3.1
  url_launcher: ^6.1.11
  desktop_window: ^0.4.0
  flutter_svg: ^2.0.7
  path_provider: ^2.0.15
  
  # Daten und Persistenz
  uuid: ^3.0.7
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  excel: ^2.1.0
  pdf: ^3.10.1
  
  # Integration mit macOS
  macos_ui: ^1.12.2
  
  # Diagramme und Visualisierungen (optional)
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1

# Flutter-Konfiguration
flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

# Plattform-spezifische Konfigurationen
# macOS-spezifische Konfiguration
macos:
  entitlements:
    - assets/macos/entitlements.plist